
const SYMBOL_DESCRIPTIONS = {
  T: "Tap this permanent",
  Q: "Untap this permanent",
  E: "An energy counter",
  P: "Modal budget pawprint",
  CHAOS: "Chaos",
  A: "An acorn counter",
  TK: "A ticket counter",
  X: "X generic mana",
  Y: "Y generic mana",
  Z: "Z generic mana",
  '0': "Zero generic mana",
  '1': "One generic mana",
  '2': "Two generic mana",
  '3': "Three generic mana",
  '4': "Four generic mana",
 '5': "Five generic mana",
  '6': "Six generic mana",
  '7': "Seven generic mana",
  '8': "Eight generic mana",
  '9': "Nine generic mana",
  '10': "Ten generic mana",
  '11': "Eleven generic mana",
  '12': "Twelve generic mana",
  '13': "Thirteen generic mana",
  '14': "Fourteen generic mana",
  '15': "Fifteen generic mana",
  '16': "Sixteen generic mana",
  '17': "Seventeen generic mana",
  '18': "Eighteen generic mana",
  '19': "Nineteen generic mana",
  '20': "Twenty generic mana",
  '100': "One hundred generic mana",
  '1000000': "One million generic mana",
  WU: "One white or blue mana",
  WB: "One white or black mana",
  BR: "One black or red mana",
  BG: "One black or green mana",
  UB: "One blue or black mana",
  UR: "One blue or red mana",
  RG: "One red or green mana",
  RW: "One red or white mana",
  GW: "One green or white mana",
  GU: "One green or blue mana",
  BGP: "One black mana, one green mana, or 2 life",
  BRP: "One black mana, one red mana, or 2 life",
  GUP: "One green mana, one blue mana, or 2 life",
  GWP: "One green mana, one white mana, or 2 life",
  RGP: "One red mana, one green mana, or 2 life",
  RWP: "One red mana, one white mana, or 2 life",
  UBP: "One blue mana, one black mana, or 2 life",
  URP: "One blue mana, one red mana, or 2 life",
  WBP: "One white mana, one black mana, or 2 life",
  WUP: "One white mana, one blue mana, or 2 life",
  CW: "One colorless mana or one white mana",
  CU: "One colorless mana or one blue mana",
  CB: "One colorless mana or one black mana",
  CR: "One colorless mana or one red mana",
  CG: "One colorless mana or one green mana",
  '2W': "Two generic mana or one white mana",
  '2U': "Two generic mana or one blue mana",
  '2B': "Two generic mana or one black mana",
  '2R': "Two generic mana or one red mana",
  '2G': "Two generic mana or one green mana",
  H: "One colored mana or two life",
  WP: "One white mana or two life",
  UP: "One blue mana or two life",
  BP: "One black mana or two life",
  RP: "One red mana or two life",
  GP: "One green mana or two life",
  CP: "One colorless mana or two life",
  W: "One white mana",
  U: "One blue mana",
  B: "One black mana",
  R: "One red mana",
  G: "One green mana",
  C: "One colorless mana",
  S: "One snow mana",
}

export default SYMBOL_DESCRIPTIONS;